### ISSUE TITLE
get_all_user_name_fields() deprecated since Moodle 3.11

### ISSUE THREAD

**Issue by top-ender** [Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports#5]
Linked form old repo:

https://github.com/jleyva/moodle-block_configurablereports/issues/247

-----

We use this plugin now with Moodle 4.3 and 4.4 and got the same error message when using the user-filters.
For a quick and dirty solution to keep the plugin running we locally changed two lines in components/filters/users:

```php
- $sort = implode(',', order_in_string(get_all_user_name_fields(), $nameformat));
+ $sort = implode(',', order_in_string(\core_user\fields::get_name_fields(), $nameformat));
- $users = $remotedb->get_records_select('user', "id " . $usql, $params, $sort, 'id,' . get_all_user_name_fields(true));
+ $users = $remotedb->get_records_select('user', "id " . $usql, $params, $sort, 'id,' . \core_user\fields::for_name()->get_sql('', true, '', '', false )->selects); 
``` 

Maybe this could support the further development of this plugin.

Regards,
Christoph

**Comment by gemguardian** [comment]
@top-ender thank you for providing this solution. We did the 4.1 update as a collabrated community project, that is been funded by 3 organization. We don't have any funds left to continue fixing issues. Though in this case I am inclided to see if we can implement the suggestion and then push to the orginal developer. 

@luukverhoeven is there time within your team to check this solutions? And if so - how much time would you need.

**Comment by luukverhoeven** [comment]
@gemguardian This approach would work for 4.3 and 4.4. Maybe the best option would be to create new separate 4.3/4.4 releases for it. I don’t think this is backwards compatible with 4.1.

We need 30-60 minutes to implement, test, and deploy it to Moodle.org/GitHub.

**Comment by gemguardian** [comment]
@top-ender after discussing it with the technical team we have decided not to move forward with this solution, since we only provided a 'update' for Moodle 4.1 

If we would release a seperated M4.3/4.4 branche the community will expect of us to move forward on this. We have no intentions to financially continue the support of this Moodle plugin. 

If you or your organization can financial fund the continous development for M4.3/44 we are more then happy to arrange this. Please send an email to sales@ltnc.nl for more information.
