### ISSUE TITLE
BUG: No filtering of results when downloading the excel report  

### ISSUE THREAD

**Issue by axiateamxo** [Lesterhuis-Training-en-Consultancy/moodle-block_configurable_reports#6]
When downloading the report (xls or csv) no filter is applied and the downloaded file always has 15000 lines. 
The report displayed on the screen is correct.  

block_configurable_reports 4.1.0 (version: 2023121803) 
Moodle 4.1.10 (Build: 20240422)

**Comment by axiateamxo** [comment]
Temporary solution:

Delete the string _amp;_ in file **/report.class.php**, in lines 349 and 353.

`$wwwpath` .= “&amp;

**Comment by calbasi** [comment]
I'm not sure if mine is the same issue as yours. In my case, when exporting to a file, the results shown are the course #1 , and not of the course I'm trying to export the results.

**Comment by calbasi** [comment]
> Temporary solution:
> 
> Delete the string _amp;_ in file **/report.class.php**, in lines 349 and 353.
> 
> `$wwwpath .= “&amp;`

My issue is not solved with this. Waiting for maintainers feedback to open a new issue or not.

**Comment by calbasi** [comment]
This merge request solves my issue:

https://github.com/jleyva/moodle-block_configurablereports/pull/248

Try it @axiateamxo !

**Comment by gemguardian** [comment]
@calbasi thank you for confirming your issue is been resolved by a patch we did. 

@axiateamxo could you please confirm if this resolves your issue as well? 

Please be aware that we did the 4.1 update as a collabrated community project, that is been funded by 3 organization. We don't have any funds left to continue fixing issues. If you are interested in funding the solution for your problem, please let us know in advance.
